#!/usr/bin/env python3
"""build_kit.py -- the Apps frameworks kit is authored ONCE, in angles/*.json.

Everything else under apps-frameworks/ that repeats an id is GENERATED from
those files (codex Phase A consult, P1): the human-readable rules twins
(angles/<angle>.rules.md), screens.json (from modules_api.SCREEN_IDS) and, from
Phase B on, kit.json with the digest over every shipped file.

    python3 build_kit.py            # (re)generate the derived files
    python3 build_kit.py --check    # exit 1 if any derived file is stale

The builder-facing files (angles/<angle>.md, profiles/*.md, templates/**) are
hand-written: they carry no ids the tests could cross-check, only plain words.
"""
import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ANGLES_DIR = os.path.join(HERE, "angles")
ANGLE_ORDER = ("product", "strategy", "design", "engineering", "backend", "frontend")
KINDS = ("page", "chat", "link")
LEVELS = ("required", "kind-required", "advisory")
V1_ASKED = ("yes", "prefilled", "end", "no")

# Design v1 scope, codex R1 P4: eighteen checks blocked "done" in kit 1.0.0. Kit 1.1.0
# (founder direction 2026-09-12, ahead of field data; RULINGS.md) promotes C2 C6 C7 C22
# C36, so twenty-three block "done".
V1_MUST_FIX = frozenset("C1 C2 C3 C4 C6 C7 C10 C11 C17 C18 C19 C20 C22 C25 C26 C28 C29 C32 C33 C35 C36 C37 C38".split())


def load_angles():
    out = []
    for name in ANGLE_ORDER:
        with open(os.path.join(ANGLES_DIR, name + ".json"), encoding="utf-8") as fh:
            out.append(json.load(fh))
    return out


def render_rules_md(angle):
    """The twin: one table of rules with their Sutra source, one of checks.
    Not builder-facing; the leak scanner does not run over it."""
    lines = ["# %s -- rules and checks (generated from %s.json; do not edit)" % (angle["angle"].capitalize(), angle["angle"]), ""]
    lines += ["| Field | Value |", "|---|---|",
              "| **status** | generated by build_kit.py; source of record is `angles/%s.json` |" % angle["angle"],
              "| **updated** | on every `build_kit.py` run |",
              "| Purpose | %s |" % angle["purpose"],
              "| Artifact | %s |" % angle.get("artifact", ""), ""]
    lines += ["## Questions", "", "| id | question | required for | optional | v1 |", "|---|---|---|---|---|"]
    for q in angle["questions"]:
        lines.append("| %s | %s | %s | %s | %s |" % (q["id"], q["question"], ", ".join(q["required_for"]) or "-", "yes" if q["optional"] else "no", q["v1_asked"]))
    lines += ["", "## Rules", "", "| id | rule | kinds | Sutra source | enforced by |", "|---|---|---|---|---|"]
    for r in angle["rules"]:
        lines.append("| %s | %s | %s | %s | %s |" % (r["id"], r["rule"], ", ".join(r["kinds"]), r["sutra_source"], r["enforced_by"]))
    lines += ["", "## Checks", "", "| id | level | kinds | v1 | what | evaluator |", "|---|---|---|---|---|---|"]
    for c in angle["checks"]:
        lines.append("| %s | %s | %s | %s | %s | %s |" % (c["id"], c["level"], ", ".join(c["kinds"]), "must-fix" if c["v1_must_fix"] else "suggest", c["what"], c["evaluator"]))
    lines += ["", "---", "provenance: generated by apps-frameworks/build_kit.py from angles/%s.json; the JSON is the single authored source (codex Phase A consult P1)." % angle["angle"], ""]
    return "\n".join(lines)


def screen_ids():
    """SCREEN_IDS lives in modules_api.py so the server, the seed payload and
    check.py agree; screens.json is its offline copy for check.py."""
    ui = os.path.dirname(HERE)
    if ui not in sys.path:
        sys.path.insert(0, ui)
    import modules_api  # noqa: E402  (pulls FastAPI; fine in the sutra-ui venv)
    return list(modules_api.SCREEN_IDS)


def render_screens_json():
    return json.dumps({"screens": screen_ids(),
                       "forbidden": ["terminal", "usage"],
                       "note": "generated by build_kit.py from modules_api.SCREEN_IDS; a link may open any id here"},
                      indent=1) + "\n"


KIT_VERSION = "1.1.0"          # bump on any change a builder would notice (questions, checks, starters)
KIT_JSON = os.path.join(HERE, "kit.json")
SKIP_IN_DIGEST = ("kit.json", "__pycache__")


def shipped_files():
    """Every file under the kit dir except kit.json itself and caches: the set
    the digest covers and the set PUBLISH-CHECK expects in the bundle."""
    out = []
    for root, dirs, files in os.walk(HERE):
        dirs[:] = [d for d in dirs if d not in SKIP_IN_DIGEST and not d.startswith(".")]
        for f in files:
            if f in SKIP_IN_DIGEST or f.startswith(".") or f.endswith(".pyc"):
                continue
            out.append(os.path.join(root, f))
    return sorted(out)


def digest_of(paths):
    h = hashlib.sha256()
    for p in sorted(paths):
        h.update(os.path.relpath(p, HERE).encode() + b"\0")
        with open(p, "rb") as fh:
            h.update(fh.read())
    return h.hexdigest()


def render_kit_json(derived):
    """kit.json is derived from the OTHER derived files plus the hand-written
    ones, so it is rendered last, against the on-disk tree as it will be after
    this run. Deterministic: no timestamp (a --check must be idempotent)."""
    paths = [p for p in shipped_files()]
    # a derived file that is about to change contributes its NEW content
    h = hashlib.sha256()
    rels = []
    for p in sorted(set(paths) | set(k for k in derived if os.path.basename(k) != "kit.json")):
        rel = os.path.relpath(p, HERE)
        if rel in SKIP_IN_DIGEST:
            continue
        rels.append(rel)
        h.update(rel.encode() + b"\0")
        if p in derived:
            h.update(derived[p].encode("utf-8"))
        else:
            with open(p, "rb") as fh:
                h.update(fh.read())
    return json.dumps({"kit": "apps-frameworks", "version": KIT_VERSION, "digest": h.hexdigest(),
                       "digest_short": h.hexdigest()[:12], "files": rels,
                       "v1_must_fix": sorted(V1_MUST_FIX, key=lambda s: int(s[1:]))}, indent=1) + "\n"


def derived_files():
    """path -> content for every generated file, kit.json last."""
    out = {}
    for angle in load_angles():
        out[os.path.join(ANGLES_DIR, angle["angle"] + ".rules.md")] = render_rules_md(angle)
    out[os.path.join(HERE, "screens.json")] = render_screens_json()
    out[KIT_JSON] = render_kit_json(out)
    return out


def load_kit():
    with open(KIT_JSON, encoding="utf-8") as fh:
        return json.load(fh)


def main(argv):
    check = "--check" in argv
    stale = []
    for path, content in derived_files().items():
        current = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if current != content:
            stale.append(os.path.relpath(path, HERE))
            if not check:
                with open(path, "w", encoding="utf-8") as fh:
                    fh.write(content)
    if check:
        if stale:
            print("stale derived files: " + ", ".join(stale))
            return 1
        print("derived files up to date")
        return 0
    print("generated %d file(s)%s" % (len(stale), (": " + ", ".join(stale)) if stale else " (none changed)"))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
