#!/usr/bin/env bash
# backfill-helper.sh — generate full YAML records for all cap-### entries in CAPABILITY-MAP.md
#
# Per CSM TODO #4 (deadline 2026-05-08). Reads cap-### rows from CAPABILITY-MAP.md
# tables (5 sections) and emits one YAML record per cap with bucket-appropriate
# required fields. Missing data is marked TBD-NEEDS-BACKFILL — sufficient for
# TODO #1 pre-commit/CI gate field-completeness validation.
#
# Output: writes records to holding/CAPABILITY-MAP-records.md (separate file to
# keep CAPABILITY-MAP.md scannable; the gate parses both).
#
# Build-layer: L1 single-instance:asawa. Promote-to plugin/scripts/ by 2026-06-01.

set -euo pipefail

ROOT="${ROOT:-${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}}"
# Asawa-mode gate (L0 promotion): silently exit on T4 fleet
[ -f "$ROOT/holding/CAPABILITY-MAP.md" ] || exit 0
CSM="$ROOT/holding/CAPABILITY-MAP.md"
OUT="$ROOT/holding/CAPABILITY-MAP-records.md"
JSONL="$ROOT/holding/state/capability-map-audit.jsonl"
TS_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

command -v jq >/dev/null 2>&1 || { echo "FATAL: jq required" >&2; exit 127; }
[ -f "$CSM" ] || { echo "FATAL: CSM not found at $CSM" >&2; exit 1; }

# Bucket inference by cap-### range
bucket_of() {
  local id="$1"
  local n=${id#cap-}
  if [ "$n" -ge 200 ] && [ "$n" -lt 300 ]; then echo "asawa-only"
  elif [ "$n" -ge 300 ] && [ "$n" -lt 400 ]; then echo "sutra-internal"
  else echo "client-shippable"
  fi
}

# Governance plane defaults by bucket
plane_of() {
  local b="$1"
  case "$b" in
    asawa-only|sutra-internal) echo "governance" ;;
    *) echo "operations" ;;
  esac
}

# Consumer defaults by bucket
consumer_of() {
  local b="$1"
  case "$b" in
    asawa-only) echo "asawa" ;;
    sutra-internal) echo "sutra" ;;
    *) echo "T4" ;;
  esac
}

# Extract cap rows from all CSM tables. Format: id|name|status
extract_caps() {
  # Bucket A index table (cap-001..011)
  awk -F'|' '/^\| cap-[0-9]+ \|/{gsub(/^ +| +$/,"",$2); gsub(/^ +| +$/,"",$3); gsub(/^ +| +$/,"",$5); print $2 "|" $3 "|" $5}' "$CSM" | sort -u
}

# Generate one YAML record
emit_record() {
  local id="$1"
  local name="$2"
  local status_arg="${3:-proposed}"
  local bucket; bucket=$(bucket_of "$id")
  local plane; plane=$(plane_of "$bucket")
  local consumer; consumer=$(consumer_of "$bucket")
  # Codex 2026-05-04 P1 fix: extract_caps grabs column 5 as status — true for Bucket A
  # and fleet-parity tables, but FALSE for Bucket B/C tables (column 5 there is
  # "Why Not Client" prose). For B/C buckets, default status to "shipping" (these
  # are existing in-use disciplines, no explicit status column).
  local status
  case "$bucket" in
    asawa-only|sutra-internal) status="shipping" ;;
    *) status="$status_arg" ;;
  esac

  cat <<RECORD
\`\`\`yaml
id: $id
name: "$name"
bucket: $bucket
governance_plane: $plane
consumer: $consumer
audience: TBD-NEEDS-BACKFILL
surface: TBD-NEEDS-BACKFILL
artifact_path: TBD-NEEDS-BACKFILL
source_of_truth_artifact: null
charter: TBD-NEEDS-BACKFILL
distribution_scope: TBD-NEEDS-BACKFILL
activation_surface: TBD-NEEDS-BACKFILL
release_vehicle: TBD-NEEDS-BACKFILL
released_in: TBD-NEEDS-BACKFILL
status: $status
version_introduced: TBD-NEEDS-BACKFILL
version_current: TBD-NEEDS-BACKFILL
created_at: 2026-05-04
deprecated_at: null
archived_at: null
last_verified_at: 2026-05-04
tests: TBD-NEEDS-BACKFILL
verification_mechanism: TBD-NEEDS-BACKFILL
owner: "Sutra Core"
direction_binding: D43
promotion_proofs:
  activation_proof: TBD-NEEDS-BACKFILL
  test_proof: TBD-NEEDS-BACKFILL
  release_proof: TBD-NEEDS-BACKFILL
  shim_ttl: null
  canonical_path_exists: TBD-NEEDS-BACKFILL
RECORD

  if [ "$bucket" = "client-shippable" ]; then
    cat <<RECORD
why_not_client_shippable: null
decommission_trigger: null
threat_model: TBD-NEEDS-BACKFILL
telemetry_coverage: TBD-NEEDS-BACKFILL
RECORD
  else
    cat <<RECORD
why_not_client_shippable: TBD-NEEDS-BACKFILL
decommission_trigger: TBD-NEEDS-BACKFILL
threat_model: null
telemetry_coverage: null
RECORD
  fi

  cat <<RECORD
depends_on: []
required_by: []
supersedes: null
replaces: null
audit_log:
  - { ts: "${TS_UTC}", action: BACKFILLED, status_to: $status, actor: backfill-helper, note: "stub generated by backfill-helper.sh per CSM TODO #4; field completion remains" }
codex_review: null
\`\`\`

RECORD
}

# Main: emit all records grouped by bucket section
{
  echo "# CAPABILITY-MAP — Full YAML records (auto-generated stubs)"
  echo
  echo "**Generated**: $TS_UTC"
  echo "**Source**: \`backfill-helper.sh\` parsing \`CAPABILITY-MAP.md\` cap-### table rows"
  echo "**Status**: stubs with TBD-NEEDS-BACKFILL placeholders for fields not derivable from table data"
  echo "**Per CSM TODO #4** (deadline 2026-05-08). Field completion is a follow-up; this file gives the gate something to validate structurally."
  echo
  echo "## Bucket A — Client-Shippable"
  echo
  while IFS='|' read -r id name status; do
    [ -z "$id" ] && continue
    [ "$(bucket_of "$id")" = "client-shippable" ] || continue
    emit_record "$id" "$name" "$status"
  done < <(extract_caps)

  echo "## Bucket B — Asawa-Only"
  echo
  while IFS='|' read -r id name status; do
    [ -z "$id" ] && continue
    [ "$(bucket_of "$id")" = "asawa-only" ] || continue
    emit_record "$id" "$name" "$status"
  done < <(extract_caps)

  echo "## Bucket C — Sutra-Internal"
  echo
  while IFS='|' read -r id name status; do
    [ -z "$id" ] && continue
    [ "$(bucket_of "$id")" = "sutra-internal" ] || continue
    emit_record "$id" "$name" "$status"
  done < <(extract_caps)
} > "$OUT"

# Count what we generated
TOTAL=$(grep -c '^id: cap-' "$OUT" 2>/dev/null || echo 0)
A=$(awk '/^## Bucket A/,/^## Bucket B/' "$OUT" | grep -c '^id: cap-')
B=$(awk '/^## Bucket B/,/^## Bucket C/' "$OUT" | grep -c '^id: cap-')
C=$(awk '/^## Bucket C/,EOF' "$OUT" | grep -c '^id: cap-')

# Append BACKFILLED audit row
jq -nc --arg ts "$TS_UTC" --arg n "$TOTAL" --arg a "$A" --arg b "$B" --arg c "$C" --arg out "$OUT" \
  '{ts:$ts, action:"BACKFILLED_BATCH", actor:"backfill-helper", note:"\($n) YAML stub records generated (Bucket A: \($a), B: \($b), C: \($c)); field completion follow-up. Output: \($out). Per CSM TODO #4.", cap_id:null, direction:"D43", script:"holding/scripts/backfill-helper.sh", output:$out}' >> "$JSONL"

echo "Records generated: $TOTAL total (A=$A, B=$B, C=$C)"
echo "Output: $OUT"
echo "Audit JSONL: $JSONL (1 row appended)"
