-- schema.sql — the whole team workspace, in one transaction, the same bytes every time.
--
-- READ THIS BEFORE CHANGING A LINE.
--
-- This file is shipped inside Sutra and run verbatim. No model writes it, nothing in it is
-- decided at runtime, and it contains NO placeholders: the workspace id is generated by the
-- database itself (gen_random_uuid) and read back afterwards, so the script that runs on the
-- tenth company is byte-identical to the one that ran on the first.
--
-- FOUR RULES IT KEEPS, ALL FOUR LOAD-BEARING:
--
--   1. ONE TRANSACTION. begin at the top, commit at the bottom. Either every table exists or
--      none does. A wifi drop halfway cannot leave a workspace that is half built, which is
--      the state nothing downstream could ever diagnose.
--
--   2. EVERY STATEMENT IS IDEMPOTENT, so a retry after that dropped wifi is harmless. Tables,
--      indexes and buckets use `if not exists` / `on conflict do nothing`. Functions use
--      `create or replace`. Triggers use `create or replace trigger` (PostgreSQL 14+; every
--      Supabase project since 2022 is 15 or newer). POLICIES ARE THE ONE EXCEPTION -- Postgres
--      has no `create policy if not exists` at any version -- so each is preceded by
--      `drop policy if exists`, which is the same thing done by hand.
--
--   3. THE `changes` LOG IS WRITTEN BY A TRIGGER, NEVER BY THE CLIENT. WORKSPACE-PLAN section 3
--      is explicit about why: a client that wrote the row and then crashed before writing the
--      log would leave a change nobody else ever hears about, and the log and the tables would
--      disagree for ever. A trigger cannot be forgotten, cannot be skipped by an old build of
--      Sutra, and cannot be got around by editing the app. `changes` has a SELECT policy and no
--      insert, update or delete policy at all, so it is append-only to everyone except the
--      trigger, which is `security definer` and therefore owned by the database, not the caller.
--
--   4. ROW LEVEL SECURITY IS ON FOR EVERY TABLE. The publishable key may read and write the rows
--      of THIS workspace and nothing else. Because each company brings its own project
--      (WORKSPACE-PLAN section 1), "this workspace" is the single row in `workspace`, and
--      public.current_workspace_id() is the one place that is decided.
--
-- MEASURED ON THE OWNER'S REAL PROJECT, 2026-09-10, and the reason the storage block at the
-- bottom exists: a publishable key CANNOT create a storage bucket. POST /storage/v1/bucket
-- answers 400 {"statusCode":"403","message":"new row violates row-level security policy"}.
-- Nothing the app holds at runtime can make the bucket, so the bucket has to be made HERE, at
-- the one moment we have admin rights. Without it the knowledge pack has nowhere to live and
-- no teammate can ever join.

begin;

-- ---------------------------------------------------------------------------------------
-- 1. THE WORKSPACE ROW, AND THE ONE PLACE "THIS WORKSPACE" IS DECIDED
-- ---------------------------------------------------------------------------------------

create table if not exists public.workspace (
  id             uuid        primary key default gen_random_uuid(),
  name           text        not null default 'Team workspace',
  schema_version integer     not null default 2,
  -- TWO COUNTERS, NOT ONE, and the reason is that the two halves of the pack publish on
  -- different terms (2026-09-10). The pack is split: a 33.6 MB core, rebuilt and re-uploaded
  -- on EVERY refresh, and a 171.5 MB index, republished only when its content hash moves. One
  -- shared counter would have to either re-upload 171 MB on every refresh to keep the number
  -- honest, or advance to a version the index never actually wrote. So each half counts
  -- itself.
  --
  -- WHAT THE COUNTER IS FOR: it is what lets two generations of a half exist at once, under
  -- different object names. Without it the index is overwritten IN PLACE, and a teammate
  -- downloading 171 MB while that replace happens can get a torn object -- half the old bytes,
  -- half the new -- which fails its checksum at best and corrupts a knowledge base at worst.
  -- The larger half is exactly where a slow download makes that race likely, which is why the
  -- half that had no counter was the wrong half to leave uncounted.
  pack_version   integer     not null default 0,   -- the core
  index_version  integer     not null default 0,   -- the meaning index
  -- SET BY THE STORAGE BLOCK AT THE BOTTOM OF THIS FILE, and the reason a client can ask "is
  -- this workspace whole?" in ONE round trip instead of eleven (2026-09-10, at the UI agent's
  -- request: the Connections tab polls once a second and eleven calls a second is not a poll,
  -- it is a denial of service on your own project).
  --
  -- It works because of rule 1 at the top: the tables are created in ONE transaction, so if
  -- this row is readable then all ten tables exist and RLS lets this key read them. The bucket
  -- is the only piece that is allowed to fail on its own -- its block catches
  -- insufficient_privilege so a storage problem cannot cost you nine tables -- so the bucket is
  -- the one thing that has to be recorded rather than inferred. Hence this column.
  --
  -- IT IS A RECORD, NOT AN OBSERVATION. A bucket deleted by hand afterwards still leaves this
  -- true. schema.verify() is the function that actually looks; schema.ready() is the cheap
  -- re-check for a workspace verify() has already passed.
  bucket_ready   boolean     not null default false,
  created_at     timestamptz not null default now()
);

-- Exactly one workspace per project, enforced by the database rather than by hope. A unique
-- index on a constant expression permits one row and rejects the second.
create unique index if not exists workspace_single_row on public.workspace ((true));

-- The version here and schema.py's SCHEMA_VERSION are the same number in two files that
-- cannot import each other, so test_workspace_core asserts they match. A fresh workspace is
-- born at the current version and needs no migration; a workspace created before a change gets
-- there through the MIGRATIONS list, because `create table if not exists` will not add a
-- column to a table that already exists. That is the whole reason the list exists.
insert into public.workspace (name, schema_version)
select 'Team workspace', 2
where not exists (select 1 from public.workspace);

-- Every other table defaults its workspace_id to this and every policy compares against it.
-- security definer so it can read `workspace` regardless of the caller's own policies, which
-- is what stops the policies from recursing into themselves.
create or replace function public.current_workspace_id() returns uuid
  language sql stable security definer set search_path = public as $fn$
  select id from public.workspace limit 1
$fn$;

-- ---------------------------------------------------------------------------------------
-- 2. THE CHANGE LOG. Created before the trigger function that writes into it.
-- ---------------------------------------------------------------------------------------

create table if not exists public.changes (
  id           bigserial   primary key,
  workspace_id uuid        not null default public.current_workspace_id(),
  kind         text        not null,          -- the table the change happened in
  op           text        not null,          -- insert | update | delete
  key          text        not null default '',
  payload      jsonb       not null default '{}'::jsonb,
  actor        text        not null default 'unknown',
  -- clock_timestamp(), AND IT MUST NOT BE CHANGED BACK TO now(). Read this before you touch it.
  --
  -- THE RACE (found 2026-09-10). `bigserial` allocates its number at INSERT, not at COMMIT, so
  -- two writers can interleave like this:
  --
  --     writer A inserts, takes id 7, its transaction is still open
  --     writer B inserts, takes id 8, and commits first
  --     a poller reads the log, sees 8, never saw 7, and sets last_seen_id = 8
  --     writer A commits. Row 7 is now visible and that client will NEVER read it.
  --
  -- A change lost that way is the worst failure this system has, worse than a crash: nothing
  -- reports it, and the two people quietly disagree for ever afterwards.
  --
  -- THE GUARD. A reader consumes only rows that are older than a lag window --
  -- `at < now() - interval '3 seconds'` -- so a row is never read until long after any
  -- transaction that could still be holding an earlier id has finished. The reader's half of
  -- this is `CHANGES_LAG_SECONDS` in seo_agent/workspace/sync.py; NEITHER HALF WORKS ALONE, so
  -- if the number moves here it moves there in the same commit. Three seconds costs a
  -- teammate at most three seconds of extra latency, which is invisible against the "about a
  -- second" the plan promises, and buys a thousand-fold margin over writes that commit in
  -- milliseconds.
  --
  -- WHY clock_timestamp() AND NOT now(). now() (and current_timestamp) is the transaction's
  -- START time. A slow transaction would stamp a time EARLIER than rows that committed before
  -- it, which is precisely backwards and would defeat the guard it is there to power.
  -- clock_timestamp() is the real wall clock at the moment of the insert. The now() defaults
  -- elsewhere in this file are ordinary record-keeping and are fine; this one column is the
  -- only clock anything depends on for ordering.
  --
  -- THE RESIDUAL, stated plainly because someone will rely on this. A transaction that stays
  -- OPEN for longer than the lag window can still be skipped. That is acceptable for what
  -- Sutra writes -- single-row REST calls that commit in milliseconds -- and it is NOT
  -- acceptable for anything batched. If any write path ever becomes a long multi-row
  -- transaction, this guard must be revisited before that path ships.
  at           timestamptz not null default clock_timestamp()
);

-- The whole sync protocol is "give me the rows past my cursor that are old enough to be safe",
-- which is one query: `at < now() - interval '3 seconds' and id > last_seen_id, order by id`.
-- (at, id) is the index that serves it; `id` alone needs no index, being the primary key.
create index if not exists changes_at_id_idx on public.changes (at, id);
create index if not exists changes_kind_idx on public.changes (kind);

-- ---------------------------------------------------------------------------------------
-- 3. THE TRIGGER THAT WRITES IT
-- ---------------------------------------------------------------------------------------
--
-- `op` is a column WORKSPACE-PLAN section 3 does not list, and it is here deliberately: the
-- plan says "deletions arrive as ordinary log rows", and a client cannot act on an ordinary
-- log row unless it can tell a delete from an update. Without `op` every consumer would have
-- to guess from the payload, which is exactly the kind of guessing this plan forbids.
--
-- The actor comes from the x-sutra-actor request header, which PostgREST publishes to the
-- session as request.headers. If it is absent (a write from the Supabase Table Editor, say)
-- we fall back to the row's own actor column, then to 'unknown'. Never to a blank, because a
-- blank in the Library reads as a bug rather than as "we do not know".

create or replace function public.log_change() returns trigger
  language plpgsql security definer set search_path = public as $fn$
declare
  row_data jsonb;
  row_key  text;
  who      text;
begin
  if (tg_op = 'DELETE') then
    row_data := to_jsonb(old);
  else
    row_data := to_jsonb(new);
  end if;

  -- A HEARTBEAT IS NOT A CHANGE. client.heartbeat() touches members.last_seen_at every minute
  -- per person so the Connections tab can show who is actually around. Logged, that would be
  -- five log rows a minute for ever, and every client would re-mirror the members table each
  -- time -- an append-only log filling up with the fact that nothing happened. So an update
  -- that changed NOTHING BUT last_seen_at is skipped. Any other change to a member (a rename,
  -- a join) still logs, because then the two sides really do differ. (2026-09-10)
  if (tg_op = 'UPDATE' and tg_table_name = 'members'
      and (to_jsonb(new) - 'last_seen_at') = (to_jsonb(old) - 'last_seen_at')) then
    return null;
  end if;

  -- The primary key is named differently in every table, so try the ones that exist. This
  -- list is the union of the primary keys declared below; adding a table means adding its
  -- key name here or the log row carries an empty key.
  row_key := coalesce(row_data->>'id', row_data->>'member_id', row_data->>'idea_id',
                      row_data->>'item_id', row_data->>'name', row_data->>'domain',
                      row_data->>'url', row_data->>'workspace_id', '');

  begin
    who := nullif(current_setting('request.headers', true)::json->>'x-sutra-actor', '');
  exception when others then
    -- A write that did not come through PostgREST has no request.headers at all. That is
    -- normal, not an error, and it must never abort the write it is logging.
    who := null;
  end;

  insert into public.changes (kind, op, key, payload, actor)
  values (tg_table_name, lower(tg_op), row_key, row_data,
          coalesce(who, row_data->>'actor', row_data->>'added_by', 'unknown'));

  return null;   -- an AFTER trigger's return value is ignored
end
$fn$;

-- ---------------------------------------------------------------------------------------
-- 4. THE EIGHT REMAINING DOMAIN TABLES
-- ---------------------------------------------------------------------------------------

create table if not exists public.members (
  member_id    text        primary key,
  workspace_id uuid        not null default public.current_workspace_id(),
  name         text        not null default '',
  joined_at    timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

-- ~1,900 rows: the asset sheet and which are ticked.
create table if not exists public.ideas (
  idea_id      text        primary key,
  workspace_id uuid        not null default public.current_workspace_id(),
  title        text        not null default '',
  kind         text        not null default '',
  ticked       boolean     not null default false,
  data         jsonb       not null default '{}'::jsonb,
  actor        text        not null default '',
  updated_at   timestamptz not null default now()
);
create index if not exists ideas_ticked_idx on public.ideas (ticked);

-- ONLY the prompts somebody edited, so this table is 0-14 rows, never the full set. An
-- unedited prompt is the one that ships with Sutra; storing all of them would mean a Sutra
-- update could never improve a prompt anybody's teammate had merely looked at.
create table if not exists public.prompts (
  name         text        primary key,
  workspace_id uuid        not null default public.current_workspace_id(),
  body         text        not null default '',
  actor        text        not null default '',
  updated_at   timestamptz not null default now()
);

create table if not exists public.competitors (
  domain       text        primary key,
  workspace_id uuid        not null default public.current_workspace_id(),
  why          text        not null default '',
  added_by     text        not null default '',
  added_at     timestamptz not null default now()
);

create table if not exists public.cta_links (
  url          text        primary key,
  workspace_id uuid        not null default public.current_workspace_id(),
  label        text        not null default '',
  why          text        not null default '',
  added_by     text        not null default '',
  added_at     timestamptz not null default now()
);

-- One row. workspace_id is the primary key, so a second row is impossible by construction
-- rather than by a rule somebody has to remember.
create table if not exists public.company (
  workspace_id uuid        primary key default public.current_workspace_id(),
  brand        text        not null default '',
  domain       text        not null default '',
  one_liner    text        not null default '',
  niche        text        not null default '',
  actor        text        not null default '',
  updated_at   timestamptz not null default now()
);

create table if not exists public.library (
  item_id      text        primary key,
  workspace_id uuid        not null default public.current_workspace_id(),
  title        text        not null default '',
  status       text        not null default 'done',
  url          text        not null default '',
  body_md      text        not null default '',
  meta         jsonb       not null default '{}'::jsonb,
  actor        text        not null default '',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index if not exists library_updated_idx on public.library (updated_at desc);

-- A DELTA, NEVER THE WHOLE SITE. The full 12,318 pages live in the knowledge pack; this table
-- carries only what changed since that pack was built, and is trimmed when the pack is
-- rebuilt. That is what keeps the database under 5 MB against a 500 MB limit, and it is only
-- correct because the pack is rebuilt on every click (WORKSPACE-PLAN section 2).
create table if not exists public.pages (
  url          text        primary key,
  workspace_id uuid        not null default public.current_workspace_id(),
  op           text        not null default 'changed',   -- changed | gone
  title        text        not null default '',
  description  text        not null default '',
  type         text        not null default '',
  word_count   integer     not null default 0,
  body         text        not null default '',
  pack_version integer     not null default 0,           -- the pack this delta is measured against
  actor        text        not null default '',
  changed_at   timestamptz not null default now()
);
create index if not exists pages_pack_idx on public.pages (pack_version);

-- ---------------------------------------------------------------------------------------
-- 5. THE TRIGGER ON EVERY DOMAIN TABLE
-- ---------------------------------------------------------------------------------------
-- Nine triggers for nine tables. `changes` itself is not in this list: logging the log would
-- recurse for ever.

create or replace trigger workspace_changed   after insert or update or delete on public.workspace   for each row execute function public.log_change();
create or replace trigger members_changed     after insert or update or delete on public.members     for each row execute function public.log_change();
create or replace trigger ideas_changed       after insert or update or delete on public.ideas       for each row execute function public.log_change();
create or replace trigger prompts_changed     after insert or update or delete on public.prompts     for each row execute function public.log_change();
create or replace trigger competitors_changed after insert or update or delete on public.competitors for each row execute function public.log_change();
create or replace trigger cta_links_changed   after insert or update or delete on public.cta_links   for each row execute function public.log_change();
create or replace trigger company_changed     after insert or update or delete on public.company     for each row execute function public.log_change();
create or replace trigger library_changed     after insert or update or delete on public.library     for each row execute function public.log_change();
create or replace trigger pages_changed       after insert or update or delete on public.pages       for each row execute function public.log_change();

-- ---------------------------------------------------------------------------------------
-- 6. ROW LEVEL SECURITY
-- ---------------------------------------------------------------------------------------
-- On for all ten tables. Every domain policy is the same sentence -- "the row belongs to this
-- workspace" -- for both reading (using) and writing (with check), so a client cannot read
-- another project's rows and cannot write a row stamped with another project's id either.
--
-- `anon` is the role a publishable key maps to; `authenticated` is included so that turning on
-- Supabase Auth later does not silently lock everybody out.
--
-- WORKSPACE-PLAN section 5: everyone can do everything. There is no owner role and no
-- permission tier. Every write carries an actor so the log can say who, and the Prompts tab's
-- Reset button is the undo.

alter table public.workspace   enable row level security;
alter table public.members     enable row level security;
alter table public.ideas       enable row level security;
alter table public.prompts     enable row level security;
alter table public.competitors enable row level security;
alter table public.cta_links   enable row level security;
alter table public.company     enable row level security;
alter table public.library     enable row level security;
alter table public.pages       enable row level security;
alter table public.changes     enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on
  public.workspace, public.members, public.ideas, public.prompts, public.competitors,
  public.cta_links, public.company, public.library, public.pages
  to anon, authenticated;
-- SELECT ONLY on the log. The trigger writes it as `security definer`, so it does not need
-- the caller to hold an insert grant -- and the caller must not hold one.
grant select on public.changes to anon, authenticated;

-- The workspace row may be read and renamed, never created or destroyed from the app. There
-- is deliberately no insert or delete policy: the row is born in this script and dies with
-- the project.
drop policy if exists workspace_read on public.workspace;
create policy workspace_read on public.workspace for select to anon, authenticated
  using (id = public.current_workspace_id());
drop policy if exists workspace_rename on public.workspace;
create policy workspace_rename on public.workspace for update to anon, authenticated
  using (id = public.current_workspace_id()) with check (id = public.current_workspace_id());

drop policy if exists members_all on public.members;
create policy members_all on public.members for all to anon, authenticated
  using (workspace_id = public.current_workspace_id())
  with check (workspace_id = public.current_workspace_id());

drop policy if exists ideas_all on public.ideas;
create policy ideas_all on public.ideas for all to anon, authenticated
  using (workspace_id = public.current_workspace_id())
  with check (workspace_id = public.current_workspace_id());

drop policy if exists prompts_all on public.prompts;
create policy prompts_all on public.prompts for all to anon, authenticated
  using (workspace_id = public.current_workspace_id())
  with check (workspace_id = public.current_workspace_id());

drop policy if exists competitors_all on public.competitors;
create policy competitors_all on public.competitors for all to anon, authenticated
  using (workspace_id = public.current_workspace_id())
  with check (workspace_id = public.current_workspace_id());

drop policy if exists cta_links_all on public.cta_links;
create policy cta_links_all on public.cta_links for all to anon, authenticated
  using (workspace_id = public.current_workspace_id())
  with check (workspace_id = public.current_workspace_id());

drop policy if exists company_all on public.company;
create policy company_all on public.company for all to anon, authenticated
  using (workspace_id = public.current_workspace_id())
  with check (workspace_id = public.current_workspace_id());

drop policy if exists library_all on public.library;
create policy library_all on public.library for all to anon, authenticated
  using (workspace_id = public.current_workspace_id())
  with check (workspace_id = public.current_workspace_id());

drop policy if exists pages_all on public.pages;
create policy pages_all on public.pages for all to anon, authenticated
  using (workspace_id = public.current_workspace_id())
  with check (workspace_id = public.current_workspace_id());

-- Append-only: read the log, never write it. This is the second half of rule 3 at the top.
drop policy if exists changes_read on public.changes;
create policy changes_read on public.changes for select to anon, authenticated
  using (workspace_id = public.current_workspace_id());

-- ---------------------------------------------------------------------------------------
-- 7. THE FILE CUPBOARD
-- ---------------------------------------------------------------------------------------
-- One bucket, `knowledge`, holding one object per pack version: pack/<version>.zip.
--
-- Measured 2026-09-10: the publishable key gets 400/"new row violates row-level security
-- policy" when it tries to make a bucket, so this is the only moment the bucket can be made.
--
-- The whole block is wrapped in an exception handler for one reason. `storage.objects` is
-- owned by supabase_storage_admin, not by the role the Management API runs as, and on some
-- projects creating a policy on it raises insufficient_privilege. If that happened outside a
-- handler it would abort the transaction and the person would get NO TABLES because of a
-- storage policy -- a nine-table failure caused by a one-bucket problem. Inside a handler the
-- subtransaction rolls back alone, the tables survive, and verify() is the thing that reports
-- the workspace as not ready. Nothing here is allowed to report success; verify() does that.

do $storage$
begin
  -- THE BUCKET'S OBJECT LIMIT, PINNED AT 45 MiB. Measured 2026-09-10: a real pack built from
  -- a clone of the owner's install is 337 MB raw and 205 MB zipped, not the ~100 MB
  -- WORKSPACE-PLAN section 3 estimated -- 84% of it is content-index/, float32 vectors that
  -- deflate to 0.89 and never will do better. Supabase Free caps a SINGLE STORED OBJECT at
  -- 50 MB, so pack/<version>.zip as one object cannot exist on the plan this whole design
  -- rests on. The pack is therefore stored as numbered parts with a sha256 sidecar written
  -- last.
  --
  -- It is set HERE, at creation, rather than left to the plan default, so the part size is
  -- DECIDED rather than discovered: a bucket made on one plan and read on another would
  -- otherwise silently change how packs are split.
  --
  -- WHY 47185920 (45 MiB) AND NOT A ROUNDER 40. The number has to clear a window at both ends.
  -- Below: pack.py sizes a part as min(PART_BYTES, limit - PART_HEADROOM) = min(40 MiB,
  -- limit - 4 MiB), so anything under 44 MiB would quietly SHRINK its parts -- pinning the
  -- limit to 40 MiB would have cut the part size to 36 MiB and made the pin the thing that
  -- changed the split it was added to stop. Above: "50 MB" is ambiguous, and 50 x 10^6 and
  -- 50 x 2^20 are four megabytes apart, so the value must sit under the SMALLER reading
  -- (50,000,000) to be safe on either. 47,185,920 clears 44 MiB and stays under 50,000,000.
  -- If pack.py's PART_BYTES or PART_HEADROOM ever move, re-check this number against them.
  --
  -- RAISING THIS LATER IS SAFE. LOWERING IT IS NOT: parts already stored at the old size would
  -- be stranded, uploadable but no longer replaceable. That asymmetry is why the conflict
  -- clause below only ever raises, which also leaves a bucket somebody made by hand in the
  -- dashboard alone if they deliberately set it higher. A null file_size_limit means "use the
  -- plan default", not "unlimited", so pinning a null up to 45 MiB is the right direction too.
  --
  -- TWO GENERATIONS OF EACH HALF ARE KEPT AT ONCE, DELIBERATELY. A teammate five minutes into
  -- downloading generation N-1 must not have it deleted underneath them. Both halves are
  -- counted -- workspace.pack_version for the core, workspace.index_version for the index, see
  -- the note on those columns -- so both can hold two. That is at most a few hundred megabytes
  -- against the 1 GB Free allowance, so it fits. Do not "tidy up" to one generation, for
  -- either half: that reintroduces the torn-download race, and it is the big half where a slow
  -- download makes it likely.
  insert into storage.buckets (id, name, public, file_size_limit)
  values ('knowledge', 'knowledge', false, 47185920)
  on conflict (id) do update
    set file_size_limit = greatest(coalesce(storage.buckets.file_size_limit, 0),
                                   excluded.file_size_limit);

  drop policy if exists knowledge_read on storage.objects;
  create policy knowledge_read on storage.objects for select to anon, authenticated
    using (bucket_id = 'knowledge');

  drop policy if exists knowledge_write on storage.objects;
  create policy knowledge_write on storage.objects for insert to anon, authenticated
    with check (bucket_id = 'knowledge');

  drop policy if exists knowledge_replace on storage.objects;
  create policy knowledge_replace on storage.objects for update to anon, authenticated
    using (bucket_id = 'knowledge') with check (bucket_id = 'knowledge');

  drop policy if exists knowledge_remove on storage.objects;
  create policy knowledge_remove on storage.objects for delete to anon, authenticated
    using (bucket_id = 'knowledge');

  -- LAST, and only if every statement above succeeded. If any of them raised, this line is
  -- never reached, the subtransaction rolls back, and bucket_ready stays false -- which is
  -- exactly what ready() and verify() should then report.
  update public.workspace set bucket_ready = true;
exception when insufficient_privilege or undefined_table then
  raise notice 'Sutra could not set up the knowledge bucket from SQL (%). The tables are fine; create a private bucket named knowledge in Storage by hand.', sqlerrm;
end
$storage$;

commit;

-- TELL POSTGREST THE TABLES EXIST. Without this, the owner's first real run reported five of the
-- ten tables missing seconds after creating all ten (2026-09-09). PostgREST serves /rest/v1 from a
-- CACHED copy of the schema and refreshes it on its own schedule, so a table created a moment ago
-- answers PGRST205 "Could not find the table in the schema cache" -- which is indistinguishable
-- from "this table was never created" unless you know to wait. Everything had worked; the check
-- ran too early. This makes the reload immediate instead of eventual.
notify pgrst, 'reload schema';

-- ---------------------------------------------------------------------------------------
-- 8. WHAT YOU SHOULD SEE WHEN THIS WORKS
-- ---------------------------------------------------------------------------------------
-- This script is a first-class deliverable, not a fallback: the realistic first run is a
-- person pasting it into the Supabase SQL Editor and pressing Run. The Editor shows the
-- result of the LAST statement, so the last statement is a report a person can read.
--
-- It is deliberately OUTSIDE the transaction above. It reads what actually landed rather
-- than what the script intended to do, which is the same rule verify() follows in Python:
-- never report success from "the statements did not error".
--
-- A good run prints one row reading:
--
--   tables_created | 10
--   triggers_armed | 9
--   policies_armed | 12
--   bucket_ready   | true
--   workspace_id   | <a uuid>
--   schema_version | 1
--   verdict        | Workspace ready. Copy the workspace id above into Sutra.
--
-- Anything other than "Workspace ready" names the missing piece, and running the script a
-- second time is safe and will fix an interrupted first run.

select
  (select count(*) from information_schema.tables
     where table_schema = 'public'
       and table_name in ('workspace','members','ideas','prompts','competitors',
                          'cta_links','company','library','pages','changes'))     as tables_created,
  (select count(*) from information_schema.triggers
     where trigger_schema = 'public' and action_statement like '%log_change%'
       and event_manipulation = 'INSERT')                                          as triggers_armed,
  (select count(*) from pg_policies
     where (schemaname = 'public'
            and tablename in ('workspace','members','ideas','prompts','competitors',
                              'cta_links','company','library','pages','changes'))
        or (schemaname = 'storage' and policyname like 'knowledge_%'))             as policies_armed,
  (select exists (select 1 from storage.buckets where id = 'knowledge'))           as bucket_ready,
  (select file_size_limit from storage.buckets where id = 'knowledge')             as max_object_bytes,
  (select id from public.workspace limit 1)                                        as workspace_id,
  (select schema_version from public.workspace limit 1)                            as schema_version,
  (select pack_version from public.workspace limit 1)                              as pack_version,
  (select index_version from public.workspace limit 1)                             as index_version,
  case
    when (select count(*) from information_schema.tables
            where table_schema = 'public'
              and table_name in ('workspace','members','ideas','prompts','competitors',
                                 'cta_links','company','library','pages','changes')) < 10
      then 'NOT READY: some tables are missing. Run this whole script again.'
    when not (select exists (select 1 from storage.buckets where id = 'knowledge'))
      then 'NOT READY: the tables are there but the knowledge bucket is not. Open Storage and create a private bucket named knowledge, then run this script again.'
    when (select count(*) from pg_policies where schemaname = 'storage' and policyname like 'knowledge_%') < 4
      then 'NOT READY: the bucket exists but its four access rules do not. Run this whole script again.'
    else 'Workspace ready. Copy the workspace id above into Sutra.'
  end                                                                              as verdict;
