"""schema.py — creating the workspace, and the one function allowed to say it worked.

THE BAR, from WORKSPACE-PLAN section 10: nothing reports success it has not verified. So the
only function in this package that returns "ready" is verify(), and it returns it after
reading the workspace back out of Supabase. create() does not report success. run_sql() does
not report success. "The request did not error" is not success and never will be.

TWO ROUTES, AND BOTH SHIP.

  1. Seamless. The person pastes a Supabase personal access token (sbp_...). Sutra POSTs
     schema.sql to https://api.supabase.com/v1/projects/{ref}/database/query, which runs it
     with admin rights. THE TOKEN IS AN ARGUMENT, USED ONCE, AND NEVER WRITTEN DOWN: it is
     not saved to connections.json, not put in the share link, not logged, and not kept on
     any object. It goes out of scope when create() returns. tests/test_workspace_core.py
     proves that by searching the whole data directory for it afterwards.

  2. Paste. Sutra shows schema.sql and a link to the project's SQL Editor. This is not a
     consolation prize -- realistically the first run goes this way, because a personal
     access token has to be generated by hand -- so schema.sql ends with a verdict row a
     person can read, and running it twice is safe.

Route 2 is offered automatically whenever route 1 fails, with the reason shown, so a person
is never stuck. That is why fallback() carries `reason`: a fallback with no explanation is
just a failure with extra steps.

WHY THE DATABASE PASSWORD IS NOT HERE. WORKSPACE-PLAN section 4, measured 2026-09-09:
db.<ref>.supabase.co resolves to IPv6 only, the owner's Mac has no IPv6 address at all, and
most Indian home broadband is the same. A direct Postgres connection can never work from
those machines. There is no psycopg in this package and there must not be one.

MIGRATIONS ARE NOT OPTIONAL. workspace.schema_version is written at creation and every later
Sutra compares its own SCHEMA_VERSION against it and applies the missing steps in order.
Without this every future change breaks every existing workspace.
"""
import os
import time
import re

from . import client, link
from ._common import TOKEN_ADVICE, TableMissing, WorkspaceError, request

HERE = os.path.dirname(os.path.abspath(__file__))
SQL_FILE = os.path.join(HERE, "schema.sql")

# HOW LONG TO GIVE POSTGREST'S SCHEMA CACHE before believing a table is missing. Two short waits,
# so a healthy workspace is never delayed and a freshly created one is not called broken. Seconds,
# in order. See verify() for the incident these exist because of.
CACHE_RETRY_WAITS = (1.5, 3.0)

# Bump this when you add a MIGRATIONS entry, never on its own. The two must move together:
# the version says what the code expects, the list says how to get there.
SCHEMA_VERSION = 3

# The ten tables every workspace has, whatever version it is on: the nine from WORKSPACE-PLAN
# section 3, plus the log. A workspace missing one of these is broken, at any version.
BASE_TABLES = ("workspace", "members", "ideas", "prompts", "competitors",
               "cta_links", "company", "library", "pages", "changes")

# TABLES A MIGRATION ADDED, and the version that added each. A workspace older than that version
# is NOT broken for lacking one -- it is behind, and migrate() is what fixes it.
#
# THIS SPLIT IS LOAD-BEARING AND IT IS NOT TIDINESS. verify() refuses to call a workspace ready
# when a table is missing, and migrate() refuses to migrate a workspace verify() has not called
# ready. So counting a not-yet-migrated table as MISSING would report the owner's live workspace
# as broken and then refuse the one operation that could fix it -- a dead end with his real
# project inside it. So verify() judges a workspace against the tables ITS OWN version should
# have, and reports the rest as `behind`.
ADDED_IN = {"brand_inputs": 3}

# Everything a workspace at SCHEMA_VERSION has. schema.sql creates all of these for a fresh one.
TABLES = BASE_TABLES + tuple(sorted(ADDED_IN))

MANAGEMENT_API = "https://api.supabase.com/v1/projects/%s/database/query"

# ---- MIGRATIONS ---------------------------------------------------------------------------
#
# An ordered list of (version, what_it_does, sql). Rules for adding one:
#
#   * APPEND, never edit an entry that has shipped. A workspace out there has already run it.
#   * The sql is the change only -- no begin/commit and no version bump. apply_one() wraps it
#     in a transaction and appends the bump itself, so the version can never be ahead of the
#     change it describes. That is the single most important property here: a crash between
#     the change and the bump would make every future Sutra skip a step that never ran.
#   * Same idempotency rules as schema.sql, because a migration gets retried too.
#   * Bump SCHEMA_VERSION above in the same commit.
#
# Example of the shape, for when the first one is needed:
#
#   (3, "give library a word count", "alter table public.library add column if not exists "
#                                    "word_count integer not null default 0;"),
MIGRATIONS = [
    # Added 2026-09-10, and the first real one. The pack is split into a core and a much larger
    # meaning index; the core was counted by pack_version and the index was not, so the index
    # was overwritten in place and a teammate downloading 171 MB during a replace could get a
    # torn object. A workspace created before today has the column missing -- `create table if
    # not exists` will not add a column to a table that already exists -- so it can only arrive
    # this way. `if not exists` on the column so running it against a workspace created from
    # today's schema.sql, which already has it, is a harmless no-op.
    (2, "count the meaning index separately from the core, so two generations of it can coexist",
     "alter table public.workspace "
     "add column if not exists index_version integer not null default 0;"),
    # Added 2026-09-10. pricing.md is the one part of the brand pack a PERSON types by hand, and
    # until now it travelled only inside the knowledge pack -- so somebody's prices reached their
    # teammates when the pack was next rebuilt (minutes) rather than through the changes log (about
    # a second), with nothing on screen saying so. `brand_inputs` is the live pipe for it. The table
    # cannot arrive any other way on a workspace that already exists: `create table if not exists`
    # in schema.sql does nothing for a database whose tables are already there.
    #
    # The whole step is idempotent, so running it against a workspace created from today's
    # schema.sql (which already has the table) is a harmless no-op. `notify pgrst` is inside the
    # transaction on purpose: notifications are delivered at commit, and without it PostgREST would
    # answer PGRST205 for the new table until its schema cache refreshed on its own schedule --
    # which is indistinguishable from "the table was never created" (the 2026-09-09 incident).
    (3, "sync the brand files a person types in, so a price reaches the team in seconds",
     "create table if not exists public.brand_inputs ("
     " name text primary key,"
     " workspace_id uuid not null default public.current_workspace_id(),"
     " body text not null default '',"
     " actor text not null default '',"
     " updated_at timestamptz not null default now());\n"
     "create or replace trigger brand_inputs_changed after insert or update or delete"
     " on public.brand_inputs for each row execute function public.log_change();\n"
     "alter table public.brand_inputs enable row level security;\n"
     "grant select, insert, update, delete on public.brand_inputs to anon, authenticated;\n"
     "drop policy if exists brand_inputs_all on public.brand_inputs;\n"
     "create policy brand_inputs_all on public.brand_inputs for all to anon, authenticated"
     " using (workspace_id = public.current_workspace_id())"
     " with check (workspace_id = public.current_workspace_id());\n"
     "notify pgrst, 'reload schema';"),
]


def sql():
    """The create script, verbatim off disk. Read every time rather than cached at import, so
    a shipped fix takes effect without a restart, and so a test can prove the file on disk is
    the file that runs."""
    with open(SQL_FILE, encoding="utf-8") as f:
        return f.read()


# A PERSON PASTING THIS IS NOT READING IT. schema.sql is 565 lines and 33,671 characters, and
# 18,600 of those are developer notes: why clock_timestamp() and not now(), why 45 MiB and not 40,
# what the bigserial race is. Every word of that earns its place IN THE REPO, where the next person
# to edit the file needs it. On screen, in front of somebody who has been told this takes thirty
# seconds, it is a wall of text that reads as "this is complicated and probably fragile" — which is
# the opposite of true, and the opposite of what the paste route is for. (2026-09-10, after the
# owner opened the screen and asked why he was being shown all this.)
#
# So the pasted script is the SQL with the essay taken out: 300 lines instead of 565. What survives
# is a short header saying what it does, and the "what you should see when this works" block, which
# is the one comment a person actually uses.
#
# ONLY WHOLE-LINE COMMENTS ARE REMOVED. An inline `--` could sit inside a string literal, and
# stripping one would corrupt the SQL rather than tidy it, so those are left exactly where they are.
# The file on disk is never modified; this is a view of it.

PASTE_HEADER = """-- Sutra team workspace — the setup script.
--
-- Safe to run twice: it either all works or none of it does.
-- The last line it prints tells you whether the workspace is ready.
"""

# The one comment block a person reads rather than skips, kept whole.
_KEEP_FROM = "-- 8. WHAT YOU SHOULD SEE WHEN THIS WORKS"


def paste_sql():
    """schema.sql with the developer notes stripped, for the screen."""
    out, keeping = [], False
    for line in sql().splitlines():
        bare = line.lstrip()
        if bare.startswith("--"):
            if _KEEP_FROM in line:
                keeping = True
            if not keeping:
                continue
        elif keeping and bare:
            keeping = False
        out.append(line)
    text = "\n".join(out)
    while "\n\n\n" in text:
        text = text.replace("\n\n\n", "\n\n")
    return PASTE_HEADER + text.lstrip("\n")


def project_ref(url):
    """The project ref out of a project URL: https://vxhx....supabase.co -> vxhx....

    The ref is what the management API addresses a project by, and the URL is the only thing
    the person was asked to paste, so it has to come from there.
    """
    text = (url or "").strip()
    match = re.search(r"https?://([a-z0-9]{16,40})\.supabase\.(co|in|net)", text, re.I)
    if match:
        return match.group(1).lower()
    # Someone pasted the ref on its own, which the Supabase dashboard also shows.
    bare = re.fullmatch(r"[a-z0-9]{16,40}", text, re.I)
    if bare:
        return text.lower()
    raise WorkspaceError(
        "That does not look like a Supabase project URL. It should read "
        "https://something.supabase.co — copy it from Project Settings, then Data API.")


def editor_url(ref):
    """Where a person pastes the script. Deep-links to that project's SQL Editor."""
    return "https://supabase.com/dashboard/project/%s/sql/new" % ref


def fallback(reason, ref=None, url=None):
    """The paste route, with the reason route 1 could not be used.

    Returned rather than raised, because this is not a failure: it is the other way of doing
    the same job, and the caller's job is to show it, not to apologise for it.
    """
    if ref is None and url:
        try:
            ref = project_ref(url)
        except WorkspaceError:
            ref = None
    return {
        "route": "paste",
        "ok": False,                 # not ready until verify() says so
        "reason": reason,
        "sql": paste_sql(),
        "editor_url": editor_url(ref) if ref else "https://supabase.com/dashboard",
        "next": "Open the SQL Editor, paste the script, press Run, then come back and press "
                "'I've run it'. The script ends by printing whether the workspace is ready.",
    }


# ---- route 1 -------------------------------------------------------------------------------

def run_sql(ref, token, statements):
    """POST SQL to the management API. Returns the rows the last statement produced.

    `token` is a personal access token and this is the only function that takes one. It is
    put in a header and nothing else: not stored, not returned, not logged. _common builds
    no message that contains a header value, which is what keeps it out of the error text too.
    """
    if not (token or "").strip():
        raise WorkspaceError("No access token was given, so Sutra cannot run the setup for you.")
    resp = request("POST", MANAGEMENT_API % ref, "run the setup script on your project",
                   headers={"Authorization": "Bearer " + token.strip(),
                            "content-type": "application/json"},
                   json_body={"query": statements}, timeout=120.0,
                   advice_401=TOKEN_ADVICE)
    try:
        return resp.json()
    except ValueError:
        return []


# ---- verify: the only function that may say "ready" -----------------------------------------

def verify(url=None, key=None):
    """Read the workspace back out of Supabase and report what is actually there.

    HOW IT LOOKS, AND WHY NOT THE OBVIOUS WAY. The obvious way is GET /rest/v1/, PostgREST's
    OpenAPI root, which lists every table in one call. Measured on the owner's real project
    2026-09-10: that endpoint answers a publishable key with 401 "Secret API key required".
    It is admin-only.

    So verify probes each expected table with a bounded select instead, and treats
    404/PGRST205 as "not created yet". That is not a workaround, it is the stronger check,
    and it must not be "simplified" back to the root endpoint later: it proves each table is
    reachable WITH THE EXACT KEY THE APP WILL USE. A table list read with a different, more
    powerful key would prove the wrong thing -- a table can exist and still be unreadable to
    the publishable key, and that workspace is broken in a way the root endpoint cannot see.

    A TABLE A MIGRATION ADDS IS NOT A MISSING TABLE. It comes back in `behind`, not in
    `missing`, and it does not make a workspace un-ready -- see the note on ADDED_IN for the
    dead end that counting it as missing would create. `needs_update` says an update is
    available on an otherwise healthy workspace, and the reason says what is not syncing
    until it is run.

    THE BUCKET COUNTS. A workspace with ten tables and no knowledge bucket is a workspace
    nobody can ever join, because the pack has nowhere to live and a publishable key cannot
    create a bucket (measured 2026-09-10, 400 "new row violates row-level security policy").
    So ok is false without it, and the reason says so.

    Returns a dict; never raises for a workspace that merely is not built yet.
    """
    if url is None or key is None:
        current = client.settings()
        url = url or current["workspace_url"].strip()
        key = key or current["workspace_key"].strip()
    if not url or not key:
        return {"ok": False, "present": [], "missing": list(BASE_TABLES),
                "behind": list(sorted(ADDED_IN)), "needs_update": False, "unreadable": {},
                "bucket": False, "workspace_id": "", "schema_version": 0,
                "reason": "No project URL and key yet, so there is nothing to check."}

    # A TABLE REPORTED MISSING IS RE-ASKED BEFORE IT IS BELIEVED, and this is not belt and braces.
    # The owner's first real run created all ten tables and was told five were missing seconds
    # later (2026-09-09). PostgREST serves /rest/v1 from a CACHED copy of the schema, so a table
    # created a moment ago answers PGRST205 -- byte-identical to the answer for a table that was
    # never created. schema.sql now ends with `notify pgrst, 'reload schema'` to make the reload
    # immediate, but that only helps a workspace built by THIS version of the script, and a reload
    # is not instantaneous even then. So a "missing" verdict is slept on and re-asked before it is
    # reported, and only a table missing on BOTH passes counts.
    #
    # The cost is paid only when something looks wrong: a healthy workspace never sleeps at all.
    present, missing, unreadable = [], [], {}

    def _probe(names):
        found, gone, bad = [], [], {}
        for table in names:
            try:
                # limit=0 asks PostgREST to name the table and hand back no rows, so the check
                # costs nothing even against `pages`, which can carry whole page bodies.
                client.select(table, limit=0, url=url, key=key)
                found.append(table)
            except TableMissing:
                gone.append(table)
            except WorkspaceError as e:
                # A table that exists but refuses to be read is NOT present. Counting it as
                # present would be the exact failure this function exists to stop.
                bad[table] = str(e)
        return found, gone, bad

    present, missing, unreadable = _probe(TABLES)

    # THE VERSION IS READ BEFORE THE RETRY, and the order is the point. A table a migration adds
    # is absent from a workspace that has not run that migration yet, and that is not a fault: it
    # is what `behind` means. Slept on and re-asked it would cost every verify() on the owner's
    # live workspace 4.5 seconds to confirm something we already knew, and counted missing it
    # would report his project broken and then block the migration that fixes it.
    workspace_id, workspace_name, schema_version = "", "", 0
    if "workspace" in present:
        try:
            row = client.one("workspace",
                             columns="id,schema_version,name,pack_version,bucket_ready",
                             url=url, key=key)
            if row:
                workspace_id = str(row.get("id") or "")
                workspace_name = str(row.get("name") or "")
                schema_version = int(row.get("schema_version") or 0)
        except WorkspaceError as e:
            unreadable["workspace(row)"] = str(e)

    behind = [t for t in missing if ADDED_IN.get(t, 0) > schema_version]
    missing = [t for t in missing if t not in behind]
    expected = [t for t in TABLES if t not in behind]

    for wait in CACHE_RETRY_WAITS:
        if not missing:
            break
        time.sleep(wait)
        again, missing, more_bad = _probe(missing)
        present.extend(again)
        unreadable.update(more_bad)
    present = [t for t in TABLES if t in present]     # keep the declared order, not probe order

    bucket = False
    bucket_error = ""
    try:
        bucket = client.bucket_exists(client.BUCKET, url=url, key=key)
    except WorkspaceError as e:
        bucket_error = str(e)

    ok = not missing and not unreadable and bucket and bool(workspace_id)
    needs_update = bool(ok and (behind or schema_version < SCHEMA_VERSION))

    if ok and needs_update:
        reason = ("Workspace ready, and an update is available: it is on version %d and this "
                  "Sutra is on version %d. Until it is updated, %s."
                  % (schema_version, SCHEMA_VERSION,
                     "the brand files a person types in travel with the knowledge pack rather "
                     "than reaching the team straight away" if "brand_inputs" in behind
                     else "some newer things will not sync"))
    elif ok:
        reason = ("Workspace ready: all %d tables, the knowledge bucket, and the workspace row."
                  % len(expected))
    elif missing and len(missing) == len(expected):
        reason = ("Nothing has been created yet. Run the setup script — none of the %d tables "
                  "exist." % len(expected))
    elif missing:
        reason = ("The setup is incomplete. These are missing: %s. Running the setup script "
                  "again is safe and will finish the job." % ", ".join(missing))
    elif unreadable:
        first = sorted(unreadable)[0]
        reason = ("The tables exist but Sutra cannot read %s with this key. %s"
                  % (first, unreadable[first]))
    elif not bucket:
        reason = ("The tables are there but the knowledge bucket is not, so no teammate could "
                  "download the knowledge pack. Run the setup script again, or create a "
                  "private bucket named '%s' under Storage." % client.BUCKET)
        if bucket_error:
            reason += " (" + bucket_error + ")"
    elif not workspace_id:
        reason = ("The tables are there but the workspace row is missing. Run the setup "
                  "script again.")
    else:
        reason = "The workspace is not ready."

    return {"ok": ok, "checked": "full", "present": present, "missing": missing,
            "behind": behind, "needs_update": needs_update,
            "unreadable": unreadable, "bucket": bucket, "workspace_id": workspace_id,
            "workspace_name": workspace_name, "schema_version": schema_version,
            "reason": reason}


def ready(url=None, key=None):
    """"Is this workspace still whole?" in ONE round trip. NOT a replacement for verify().

    WHY THIS CAN EXIST AT ALL. verify() is eleven calls, and the Connections tab polls about
    once a second (2026-09-10). Eleven calls a second against your own project is not a poll.
    But the tables do not need probing one by one to answer the resting-state question,
    because of rule 1 of schema.sql: THE TABLES ARE CREATED IN ONE TRANSACTION. Either all of
    them exist or none does. So a `workspace` row that this key can read proves the rest of
    that workspace's tables exist and that RLS lets this key read them. A table added later by
    a MIGRATION is the one thing this cannot prove, which is why the row's own
    `schema_version` comes back with it and `needs_update` says whether a step is outstanding. The bucket is the single piece that is
    allowed to fail on its own -- its block catches insufficient_privilege deliberately, so a
    storage problem cannot cost somebody nine tables -- and that is precisely why schema.sql
    records it in `workspace.bucket_ready` instead of leaving it to be inferred.

    WHAT IT IS NOT. bucket_ready is a RECORD of what happened at creation, not an observation
    of what is true now: a bucket deleted by hand afterwards still leaves it true. So this
    function may not be used to report a workspace ready for the FIRST time. create(),
    confirm() and join() all go through verify(), which actually looks. This is the cheap
    re-check afterwards, and `checked: "shallow"` on the result says so to whoever renders it.

    Returns the same keys verify() does, so a caller can treat them alike.
    """
    if url is None or key is None:
        current = client.settings()
        url = url or current["workspace_url"].strip()
        key = key or current["workspace_key"].strip()
    blank = {"ok": False, "checked": "shallow", "bucket": False, "workspace_id": "",
             "workspace_name": "", "schema_version": 0, "pack_version": 0,
             "needs_update": False}
    if not url or not key:
        return dict(blank, reason="No project URL and key yet, so there is nothing to check.")
    try:
        row = client.one("workspace",
                         columns="id,name,schema_version,pack_version,bucket_ready",
                         url=url, key=key)
    except TableMissing:
        return dict(blank, reason="This workspace has not been created yet. Run the setup "
                                  "script from the Connections tab.")
    except WorkspaceError as e:
        return dict(blank, reason=str(e))
    if not row:
        return dict(blank, reason="The tables are there but the workspace row is missing. "
                                  "Run the setup script again.")
    bucket = bool(row.get("bucket_ready"))
    out = {"ok": bucket, "checked": "shallow", "bucket": bucket,
           "workspace_id": str(row.get("id") or ""),
           "workspace_name": str(row.get("name") or ""),
           "schema_version": int(row.get("schema_version") or 0),
           "pack_version": int(row.get("pack_version") or 0)}
    # The version costs nothing here -- it is a column of the row already read -- and it is what
    # sync.push asks before it queues a change into a table a migration added.
    out["needs_update"] = out["schema_version"] < SCHEMA_VERSION
    out["reason"] = ("Workspace ready." if bucket else
                     "The tables are there but the knowledge bucket is not, so no teammate "
                     "could download the knowledge pack. Run the setup script again.")
    return out


# ---- create ---------------------------------------------------------------------------------

def create(url, key, token=None, member_name=None, save=True):
    """Build the workspace. Returns a dict the Connections tab can render as-is.

    Success shape:  {"route": "seamless"|"paste", "ok": True, "workspace_id": ..., ...}
    Fallback shape: {"route": "paste", "ok": False, "reason": ..., "sql": ..., "editor_url": ...}

    The order is deliberate:

      1. if a token was given, run the script through the management API
      2. verify(), ALWAYS, whichever way step 1 went
      3. report success only if verify said so

    Step 3 is why a token that returns 200 but leaves half a schema behind cannot be reported
    as a working workspace. And step 2 runs even with no token at all, because the person may
    already have pasted the script into the SQL Editor before pressing the button — checking
    first costs one call and saves them doing it twice.
    """
    url = (url or "").strip().rstrip("/")
    key = (key or "").strip()
    if not url or not key:
        raise WorkspaceError(
            "Sutra needs both the project URL and the publishable key. Both are on the "
            "Supabase dashboard under Project Settings, then Data API.")
    if key.startswith("sb_secret_") or key.startswith("sbp_") or "service_role" in key:
        # WORKSPACE-PLAN section 5. A secret key bypasses Row Level Security, so a workspace
        # built on one would hand every teammate admin rights over the whole project.
        raise WorkspaceError(
            "That is a secret key. Sutra only ever uses the publishable key, the one that "
            "starts with sb_publishable_, because it is the only one safe to put in a share "
            "link. Copy that one instead.")

    ref = project_ref(url)

    already = verify(url, key)
    if already["ok"]:
        if save:
            _remember(url, key, already["workspace_id"], already.get("workspace_name", ""))
            already["member"] = _enrol(member_name, url, key, already)
        already["route"] = "already"
        already["message"] = "This project already has a workspace. Sutra connected to it."
        return already

    if (token or "").strip():
        try:
            report = run_sql(ref, token, sql())
        except WorkspaceError as e:
            # The token was wrong, expired, or for another account. Route 2, with the reason.
            return fallback("Sutra could not run the setup for you: %s" % e, ref=ref)
        # THE SCRIPT RAN. That is still not success. Only verify() decides.
        checked = verify(url, key)
        if not checked["ok"]:
            return fallback(
                "The setup script ran but the workspace is not complete. %s" % checked["reason"],
                ref=ref)
        if save:
            _remember(url, key, checked["workspace_id"], checked.get("workspace_name", ""))
            checked["member"] = _enrol(member_name, url, key, checked)
        checked["route"] = "seamless"
        checked["report"] = report
        checked["message"] = "Workspace created."
        return checked
        # `token` goes out of scope here and was never written anywhere.

    return fallback(
        "Sutra has no access token, so it cannot create the tables for you. " + already["reason"],
        ref=ref)


def confirm(url=None, key=None, member_name=None, save=True):
    """What the 'I've run it' button calls after the paste route. Verify, then remember.

    A thin wrapper on purpose: the paste route and the seamless route must be judged by the
    same function, or the two would drift and one of them would start reporting success it
    had not checked.
    """
    if url is None or key is None:
        current = client.settings()
        url = url or current["workspace_url"].strip()
        key = key or current["workspace_key"].strip()
    checked = verify(url, key)
    checked["route"] = "paste"
    if checked["ok"] and save:
        _remember(url, key, checked["workspace_id"], checked.get("workspace_name", ""))
        checked["message"] = "Workspace created."
    return checked


def join(link_text, name=None, save=True):
    """A teammate joining: read the link, check the workspace is real, take a seat.

    The order matters and it is the same order as create(): VERIFY FIRST, enrol second. A
    person whose link points at a half-built workspace must be told that, not quietly added to
    a members table in a project that cannot hold their Library.

    read_link() has already refused anything carrying a secret key or a personal access token
    by the time this runs, so what reaches Supabase here can only ever read and write rows of
    one workspace.
    """
    url, key, workspace_id = link.read_link(link_text)
    checked = verify(url, key)
    checked["route"] = "join"
    if not checked["ok"]:
        return checked
    if checked["workspace_id"] and workspace_id and checked["workspace_id"] != workspace_id:
        # The link names a workspace and the project holds a different one. Almost certainly an
        # old link from before the project was rebuilt, and silently joining the new one would
        # put somebody in a workspace nobody meant to invite them to.
        return dict(checked, ok=False,
                    reason="That link is for a different workspace than the one in this "
                           "project. Ask your teammate for a fresh link from their "
                           "Connections tab.")
    if save:
        _remember(url, key, checked["workspace_id"], checked.get("workspace_name", ""))
        checked["member"] = _enrol(name, url, key, checked)
        checked["message"] = "Joined."
    return checked


def _enrol(name, url, key, checked):
    """Take a seat in the members table. Idempotent, and never fatal.

    A person whose member row could not be written is still connected -- their Library and
    their prompts work -- they simply do not appear in "who is in it" until the next
    heartbeat. Failing the whole join for that would be trading a working workspace for a
    cosmetic list.
    """
    try:
        return client.register_member(name, url=url, key=key,
                                      workspace_id=checked.get("workspace_id") or None)
    except WorkspaceError as e:
        return {"ok": False, "error": str(e)}


def _remember(url, key, workspace_id, workspace_name=""):
    """The public things, into connections.json. Never the token."""
    fields = {"workspace_url": url, "workspace_key": key, "workspace_id": workspace_id}
    if workspace_name:
        fields["workspace_name"] = workspace_name
    client.save_settings(**fields)


# ---- migrations ------------------------------------------------------------------------------

def pending(current_version):
    """The migration steps this workspace has not run, in order."""
    version = int(current_version or 0)
    return [m for m in sorted(MIGRATIONS, key=lambda m: m[0])
            if version < m[0] <= SCHEMA_VERSION]


def migration_sql(step):
    """One migration as the SQL that will actually be sent: the change, then the version bump,
    in one transaction.

    The bump is appended here rather than written into each entry so it can never be
    forgotten and can never be in a separate transaction from the change it describes. A
    workspace whose schema_version is ahead of its schema would make every future Sutra skip
    a step that never ran, and nothing downstream could detect it.
    """
    version, _what, statements = step
    return ("begin;\n%s\nupdate public.workspace set schema_version = %d;\ncommit;"
            % (statements.strip(), int(version)))


def migrate(url=None, key=None, token=None):
    """Bring a workspace up to SCHEMA_VERSION. Returns a dict, same shapes as create().

    Applies the missing steps IN ORDER and stops at the first one that fails, so a workspace
    is never left with step 4 applied and step 3 not. Without a token it returns the paste
    route carrying only the steps that are actually missing, not the whole create script.
    """
    if url is None or key is None:
        current = client.settings()
        url = url or current["workspace_url"].strip()
        key = key or current["workspace_key"].strip()

    checked = verify(url, key)
    if not checked["ok"]:
        return {"route": "blocked", "ok": False, "applied": [],
                "reason": "This workspace is not complete, so Sutra will not migrate it. "
                          + checked["reason"]}

    steps = pending(checked["schema_version"])
    if not steps:
        return {"route": "none", "ok": True, "applied": [],
                "schema_version": checked["schema_version"],
                "reason": "Already up to date (version %d)." % checked["schema_version"]}

    if not (token or "").strip():
        joined = "\n\n".join(migration_sql(s) for s in steps)
        result = fallback(
            "This workspace is on version %d and Sutra is on version %d. Sutra has no access "
            "token, so run these %d update steps in the SQL Editor."
            % (checked["schema_version"], SCHEMA_VERSION, len(steps)),
            url=url)
        result["sql"] = joined                       # the steps, never the whole create script
        result["applied"] = []
        result["steps"] = [(s[0], s[1]) for s in steps]
        return result

    ref = project_ref(url)
    applied = []
    for step in steps:
        try:
            run_sql(ref, token, migration_sql(step))
        except WorkspaceError as e:
            return {"route": "seamless", "ok": False, "applied": applied,
                    "reason": "Update step %d (%s) failed, so Sutra stopped there and left "
                              "the later steps unapplied: %s" % (step[0], step[1], e)}
        applied.append(step[0])

    after = verify(url, key)
    ok = after["ok"] and after["schema_version"] >= SCHEMA_VERSION
    return {"route": "seamless", "ok": ok, "applied": applied,
            "schema_version": after["schema_version"],
            "reason": ("Updated to version %d." % after["schema_version"]) if ok else after["reason"]}
